name: inutile-cards-backend
region: fra

services:
  - name: api
    source_dir: /backend
    
    build_command: npm install && npm run build
    
    run_command: npm start
    
    environment_slug: node-js
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: HOST
        value: "0.0.0.0"
      - key: MONGODB_URI
        value: ${MONGODB_URI}
        type: SECRET
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        type: SECRET
      - key: FRONTEND_URL
        value: https://inutile.cards
